server:
  servlet:
    context-path: "/api"

spring:
  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "ada"
    driver-class-name: org.postgresql.Driver